### ISSUE TITLE
Error while docker-compose up with a backup restore 

### ISSUE THREAD

**Issue by gemad** [kernelci/lava-docker#165]
Hello, 

I got the following error while trying to restore a backup on both #bacc75a4 and on #cac7cdd9.

```
master1_1      | Restore database from backup
master1_1      | SET
master1_1      | SET
master1_1      | SET
master1_1      | SET
master1_1      | SET
master1_1      |  set_config 
master1_1      | ------------
master1_1      |  
master1_1      | (1 row)
.
.
.
lab-slave-0_1  | Wait for master.... (1180s remains)
master1_1      | Operations to perform:
master1_1      |   Apply all migrations: admin, auth, authtoken, contenttypes, lava_results_app, lava_scheduler_app, linaro_django_xmlrpc, sessions, sites
master1_1      | Running migrations:
master1_1      |   Applying lava_results_app.0019_auto_20230512_1042...Traceback (most recent call last):
master1_1      |   File "/usr/lib/python3/dist-packages/django/db/backends/utils.py", line 84, in _execute
master1_1      |     return self.cursor.execute(sql, params)
master1_1      | psycopg2.errors.UndefinedTable: table "lava_results_app_actiondata" does not exist
master1_1      | 
master1_1      | 
master1_1      | The above exception was the direct cause of the following exception:
master1_1      | 
master1_1      | Traceback (most recent call last):
master1_1      |   File "/usr/bin/lava-server", line 68, in <module>
master1_1      |     main()
master1_1      |   File "/usr/bin/lava-server", line 64, in main
master1_1      |     execute_from_command_line([sys.argv[0]] + options.command)
master1_1      |   File "/usr/lib/python3/dist-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
master1_1      |     utility.execute()
master1_1      |   File "/usr/lib/python3/dist-packages/django/core/management/__init__.py", line 375, in execute
master1_1      |     self.fetch_command(subcommand).run_from_argv(self.argv)
master1_1      |   File "/usr/lib/python3/dist-packages/django/core/management/base.py", line 323, in run_from_argv
master1_1      |     self.execute(*args, **cmd_options)
master1_1      |   File "/usr/lib/python3/dist-packages/django/core/management/base.py", line 364, in execute
master1_1      |     output = self.handle(*args, **options)
master1_1      |   File "/usr/lib/python3/dist-packages/django/core/management/base.py", line 83, in wrapped
master1_1      |     res = handle_func(*args, **kwargs)
master1_1      |   File "/usr/lib/python3/dist-packages/django/core/management/commands/migrate.py", line 232, in handle
master1_1      |     post_migrate_state = executor.migrate(
master1_1      |   File "/usr/lib/python3/dist-packages/django/db/migrations/executor.py", line 117, in migrate
master1_1      |     state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
master1_1      |   File "/usr/lib/python3/dist-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
master1_1      |     state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
master1_1      |   File "/usr/lib/python3/dist-packages/django/db/migrations/executor.py", line 245, in apply_migration
master1_1      |     state = migration.apply(state, schema_editor)
master1_1      |   File "/usr/lib/python3/dist-packages/django/db/migrations/migration.py", line 124, in apply
master1_1      |     operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
master1_1      |   File "/usr/lib/python3/dist-packages/django/db/migrations/operations/models.py", line 261, in database_forwards
master1_1      |     schema_editor.delete_model(model)
master1_1      |   File "/usr/lib/python3/dist-packages/django/db/backends/base/schema.py", line 325, in delete_model
master1_1      |     self.execute(self.sql_delete_table % {
master1_1      |   File "/usr/lib/python3/dist-packages/django/db/backends/base/schema.py", line 137, in execute
master1_1      |     cursor.execute(sql, params)
master1_1      |   File "/usr/lib/python3/dist-packages/django/db/backends/utils.py", line 67, in execute
master1_1      |     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
master1_1      |   File "/usr/lib/python3/dist-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
master1_1      |     return executor(sql, params, many, context)
master1_1      |   File "/usr/lib/python3/dist-packages/django/db/backends/utils.py", line 84, in _execute
master1_1      |     return self.cursor.execute(sql, params)
master1_1      |   File "/usr/lib/python3/dist-packages/django/db/utils.py", line 89, in __exit__
master1_1      |     raise dj_exc_value.with_traceback(traceback) from exc_value
master1_1      |   File "/usr/lib/python3/dist-packages/django/db/backends/utils.py", line 84, in _execute
master1_1      |     return self.cursor.execute(sql, params)
master1_1      | django.db.utils.ProgrammingError: table "lava_results_app_actiondata" does not exist
master1_1      | 
.
.
.
```
step to reproduce : 

```
$./backup.sh
$cp ./backup-latest/* output/local/master/backup/
$cd output/local
$docker-compose build
$docker-compose down
$docker-compose up 
```

this problem is also confirmed by @montjoie  @ https://github.com/montjoie/lava-docker/actions/runs/4958288353/jobs/8870970915

Thanks

**Comment by montjoie** [comment]
Please re-open if the fix does not work for you. Thanks for the report
